name: Update Release Branch

on:
  push:
    branches:
      - main

jobs:
  update-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Prepare Release Branch
        run: |
          set -e  # Exit on any error

          # Configurable variables
          LIBRARY_NAME="SimpleLibrary"

          echo "Switching to main branch..."
          git checkout main

          echo "Deleting release branch if it exists..."
          git branch -D release || true

          echo "Creating and switching to release branch..."
          git checkout -B release

          echo "Checking if lib/$LIBRARY_NAME exists in main branch..."
          if [ ! -d "lib/$LIBRARY_NAME" ]; then
            echo "Error: lib/$LIBRARY_NAME does not exist in the main branch."
            exit 1
          fi

          echo "Removing everything except files specified..."
          find . -mindepth 1 \
            -name '.git' -prune -o \
            -name 'README.md' -prune -o \
            -name '.gitignore' -prune -o \
            -path "./lib/$LIBRARY_NAME" -prune -o \
            -exec rm -rf {} +

          echo "Moving library contents to the root directory..."
          mv lib/"$LIBRARY_NAME"/* . || { echo "Error: Failed to move files from lib"; exit 1; }
          rm -rf lib

          echo "Staging and committing changes..."
          git add .
          git commit -m "Update release branch" || echo "No changes to commit"

          echo "Pushing release branch to origin..."
          git push origin release --force

      - name: Verify Release Branch
        run: |
          git fetch origin release
          git checkout release
          echo "Release branch updated successfully!"
