name: Update Main Branch

on:
  push:
    branches:
      - dev

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensure latest version

      - name: Update Main Branch
        run: |
          set -e  # Exit on any error

          # Configurable variables
          LIBRARY_NAME="SimpleLibrary"  # Change this to the name of your library

          echo "Switching to dev branch..."
          git checkout dev

          echo "Checking if lib/$LIBRARY_NAME exists in dev branch..."
          if [ ! -d "lib/$LIBRARY_NAME" ]; then
            echo "Error: lib/$LIBRARY_NAME does not exist in the dev branch."
            exit 1
          fi

          echo "Removing everything except files specified..."
          find . -mindepth 1 \
            -name '.git' -prune -o \
            -name 'README.md' -prune -o \
            -name '.gitignore' -prune -o \
            -path './lib' -prune -o \
            -exec rm -rf {} +

          echo "Moving library contents to the root directory..."
          mv lib/"$LIBRARY_NAME"/* . || { echo "Error: Failed to move files from lib"; exit 1; }
          rm -rf lib

          echo "Staging and committing changes..."
          git add .
          git commit -m "Update main branch from dev" || echo "No changes to commit"

          echo "Force-pushing dev to main branch..."
          git push origin dev:main --force

          echo "Fetching and verifying main branch..."
          git fetch origin main
          git log origin/main -n 1
